-- MySQL Script generated by MySQL Workbench
-- 11/08/16 20:17:08
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gimnasio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gimnasio
-- -----------------------------------------------------
DROP DATABASE if exists `gimnasio`;
CREATE DATABASE IF NOT EXISTS `gimnasio` DEFAULT CHARACTER SET utf8 ;
USE `gimnasio` ;


-- -----------------------------------------------------
-- Table `gimnasio`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gimnasio`.`Usuario` (
  `dni` VARCHAR(9) NOT NULL,
  `password` VARCHAR(45) NULL,
  `nombreusuario` VARCHAR(45) NULL,
  `idioma` VARCHAR(3) NULL,
  `correo` VARCHAR(45) NULL,
  `tipousuario` VARCHAR(15) NULL,
  PRIMARY KEY (`dni`))
ENGINE = InnoDB;

INSERT INTO `Usuario` (`dni`, `password`, `nombreusuario`, `idioma`, `correo`, `tipousuario`) VALUES
('44466729R', '21232f297a57a5a743894a0e4a801fc3', 'edgard', 'esp', 'test@test.com', 'admin'),
('44466728R', '21232f297a57a5a743894a0e4a801fc3', 'dani', 'esp', 'test@test.com', 'admin'),
('44444727R', '21232f297a57a5a743894a0e4a801fc3', 'moncho', 'esp', 'test@test.com', 'admin');


-- -----------------------------------------------------
-- Table `gimnasio`.`SesionEntrenamiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gimnasio`.`SesionEntrenamiento` (
  `idsesion` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `horainicio` DATETIME NULL,
  `horafin` DATETIME NULL,
  `nombreactividad` VARCHAR(45) NULL,
  `nombretablaejercicios` VARCHAR(45) NULL,
  `Usuario_dni` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`idsesion`, `Usuario_dni`),
  INDEX `fk_SesionEntrenamiento_Usuario_idx` (`Usuario_dni` ASC),
  CONSTRAINT `fk_SesionEntrenamiento_Usuario`
    FOREIGN KEY (`Usuario_dni`)
    REFERENCES `gimnasio`.`Usuario` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gimnasio`.`Actividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gimnasio`.`Actividad` (
  `idactividad` INT NOT NULL AUTO_INCREMENT,
  `nombreactividad` VARCHAR(45) NULL,
  `horainicio` DATETIME NULL,
  `horafin` DATETIME NULL,
  `responsable` VARCHAR(45) NULL,
  `tipoactividad` INT NULL,
  `numplazasmax` INT NULL,
  `SesionEntrenamiento_idsesion` INT NOT NULL,
  `SesionEntrenamiento_Usuario_dni` VARCHAR(9) NOT NULL,
  `Usuario_dni` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`idactividad`),
  INDEX `fk_Actividad_SesionEntrenamiento1_idx` (`SesionEntrenamiento_idsesion` ASC, `SesionEntrenamiento_Usuario_dni` ASC),
  INDEX `fk_Actividad_Usuario1_idx` (`Usuario_dni` ASC),
  CONSTRAINT `fk_Actividad_SesionEntrenamiento1`
    FOREIGN KEY (`SesionEntrenamiento_idsesion` , `SesionEntrenamiento_Usuario_dni`)
    REFERENCES `gimnasio`.`SesionEntrenamiento` (`idsesion` , `Usuario_dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Actividad_Usuario1`
    FOREIGN KEY (`Usuario_dni`)
    REFERENCES `gimnasio`.`Usuario` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gimnasio`.`TablaEjercicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gimnasio`.`TablaEjercicios` (
  `idtabla` INT NOT NULL AUTO_INCREMENT,
  `nombretabla` VARCHAR(45) NULL,
  `tipotabla` INT NULL,
  `responsable` VARCHAR(45) NULL,
  `niveldificultadglobal` INT NULL,
  `Actividad_idactividad` INT NOT NULL,
  PRIMARY KEY (`idtabla`, `Actividad_idactividad`),
  INDEX `fk_TablaEjercicios_Actividad1_idx` (`Actividad_idactividad` ASC),
  CONSTRAINT `fk_TablaEjercicios_Actividad1`
    FOREIGN KEY (`Actividad_idactividad`)
    REFERENCES `gimnasio`.`Actividad` (`idactividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gimnasio`.`Ejercicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gimnasio`.`Ejercicio` (
  `idejercicio` INT NOT NULL AUTO_INCREMENT,
  `nombreejercicio` VARCHAR(45) NULL,
  `tipoejercicio` VARCHAR(45) NULL,
  `niveldificultad` INT NULL,
  PRIMARY KEY (`idejercicio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gimnasio`.`Notificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gimnasio`.`Notificacion` (
  `idnotificacion` INT NOT NULL AUTO_INCREMENT,
  `nombrenotificacion` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `tiponotificacion` INT NULL,
  `Usuario_dni` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`idnotificacion`, `Usuario_dni`),
  INDEX `fk_Notificacion_Usuario1_idx` (`Usuario_dni` ASC),
  CONSTRAINT `fk_Notificacion_Usuario1`
    FOREIGN KEY (`Usuario_dni`)
    REFERENCES `gimnasio`.`Usuario` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gimnasio`.`Ejercicio_has_TablaEjercicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gimnasio`.`Ejercicio_has_TablaEjercicios` (
  `Ejercicio_idejercicio` INT NOT NULL,
  `TablaEjercicios_idtabla` INT NOT NULL,
  `TablaEjercicios_Actividad_idactividad` INT NOT NULL,
  `anotaciones` VARCHAR(300) NULL,
  PRIMARY KEY (`Ejercicio_idejercicio`, `TablaEjercicios_idtabla`, `TablaEjercicios_Actividad_idactividad`),
  INDEX `fk_Ejercicio_has_TablaEjercicios_TablaEjercicios1_idx` (`TablaEjercicios_idtabla` ASC, `TablaEjercicios_Actividad_idactividad` ASC),
  INDEX `fk_Ejercicio_has_TablaEjercicios_Ejercicio1_idx` (`Ejercicio_idejercicio` ASC),
  CONSTRAINT `fk_Ejercicio_has_TablaEjercicios_Ejercicio1`
    FOREIGN KEY (`Ejercicio_idejercicio`)
    REFERENCES `gimnasio`.`Ejercicio` (`idejercicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ejercicio_has_TablaEjercicios_TablaEjercicios1`
    FOREIGN KEY (`TablaEjercicios_idtabla` , `TablaEjercicios_Actividad_idactividad`)
    REFERENCES `gimnasio`.`TablaEjercicios` (`idtabla` , `Actividad_idactividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


GRANT USAGE ON * . * TO  'admingym'@'%' IDENTIFIED BY  'admingym' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;
DROP USER 'admingym'@'%';
CREATE USER 'admingym'@'%' IDENTIFIED BY  'admingym';


GRANT ALL PRIVILEGES ON  `gimnasio` . * TO  'admingym'@'%';